const AUTO_COMPLETE_DELAY = 300;

const SELECTED_EL_COLOR = '#f1f2f6';

const MAXIMUM_SUGGESTIONS = 11;

const INITIAL_SELECTED_IDX = -1;

export { AUTO_COMPLETE_DELAY, SELECTED_EL_COLOR, MAXIMUM_SUGGESTIONS, INITIAL_SELECTED_IDX }